// Copyright (c) DSoftStudio. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace DSoftStudio.Mediator.Generators;

/// <summary>
/// Incremental source generator that detects all implementations of
/// INotificationHandler&lt;TNotification&gt; and generates compile-time
/// dispatch tables that eliminate runtime service enumeration.
/// </summary>
[Generator]
public sealed class NotificationGenerator : IIncrementalGenerator
{
    private const string HandlerInterfaceMetadataName =
        "DSoftStudio.Mediator.Abstractions.INotificationHandler`1";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var hasHandlerInterface = context.CompilationProvider
            .Select(static (compilation, _) =>
                compilation.GetTypeByMetadataName(HandlerInterfaceMetadataName) is not null);

        var handlerInfos = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) =>
                    node is ClassDeclarationSyntax { BaseList: not null },
                transform: static (ctx, ct) => GetHandlerInfo(ctx, ct))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!.Value);

        var localCollected = handlerInfos.Collect();

        // Scan referenced assemblies for INotificationHandler registrations
        var externalHandlers = context.CompilationProvider
            .Select(static (compilation, _) =>
            {
                var external = ReferencedAssemblyScanner.GetExternalNotificationHandlers(compilation);
                var array = external
                    .Select(e => new NotificationHandlerInfo(e.NotificationType, e.HandlerType))
                    .OrderBy(static h => h.NotificationType)
                    .ThenBy(static h => h.HandlerType)
                    .ToArray();
                return new EquatableArray<NotificationHandlerInfo>(array);
            });

        var combined = localCollected
            .Combine(hasHandlerInterface)
            .Combine(externalHandlers);

        context.RegisterSourceOutput(combined, static (spc, pair) =>
        {
            var ((localHandlers, interfaceExists), external) = pair;

            if (!interfaceExists && external.Length == 0)
            {
                spc.AddSource(
                    "NotificationDispatch.g.cs",
                    SourceText.From(
                        GenerateCode(new List<NotificationHandlerInfo>()),
                        Encoding.UTF8));
                return;
            }

            // Merge local + external, deduplicate
            var localList = localHandlers.IsDefaultOrEmpty
                ? Enumerable.Empty<NotificationHandlerInfo>()
                : localHandlers.Distinct();

            var registrations = localList
                .Concat(external)
                .Distinct()
                .OrderBy(static h => h.NotificationType)
                .ThenBy(static h => h.HandlerType)
                .ToList();

            var code = GenerateCode(registrations);

            spc.AddSource(
                "NotificationDispatch.g.cs",
                SourceText.From(code, Encoding.UTF8));
        });
    }

    private static NotificationHandlerInfo? GetHandlerInfo(
        GeneratorSyntaxContext ctx,
        CancellationToken ct)
    {
        var classDeclaration = (ClassDeclarationSyntax)ctx.Node;

        if (ctx.SemanticModel.GetDeclaredSymbol(classDeclaration, ct)
            is not INamedTypeSymbol symbol)
            return null;

        if (symbol.IsAbstract ||
            symbol.TypeKind != TypeKind.Class ||
            symbol.TypeParameters.Length > 0)
            return null;

        if (HandlerDiscovery.IsFileLocal(classDeclaration))
            return null;

        if (!HandlerDiscovery.TryGetNotificationHandler(
                symbol, ct, out var notificationType, out var handlerType))
            return null;

        return new NotificationHandlerInfo(notificationType, handlerType);
    }

    private static string GenerateCode(List<NotificationHandlerInfo> registrations)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace DSoftStudio.Mediator");
        sb.AppendLine("{");

        // Group handlers by notification type
        var groups = registrations
            .GroupBy(static r => r.NotificationType)
            .OrderBy(static g => g.Key)
            .ToList();

        // Registry class that populates NotificationDispatch<T>.Handlers
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Auto-generated notification dispatch registry.");
        sb.AppendLine("    /// Precompiles all notification dispatch tables at application startup.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    internal static class NotificationRegistry");
        sb.AppendLine("    {");
        sb.AppendLine("        public static void Register()");
        sb.AppendLine("        {");

        foreach (var group in groups)
        {
            var handlersInGroup = group.OrderBy(static h => h.HandlerType).ToList();

            sb.AppendLine($"            global::DSoftStudio.Mediator.NotificationDispatch<{group.Key}>.TryInitialize(");
            sb.AppendLine($"                new global::System.Func<global::System.IServiceProvider, global::DSoftStudio.Mediator.Abstractions.INotificationHandler<{group.Key}>>[]");
            sb.AppendLine("                {");

            foreach (var handler in handlersInGroup)
            {
                sb.AppendLine($"                    static sp => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{handler.HandlerType}>(sp),");
            }

            sb.AppendLine("                });");
            sb.AppendLine();

            // AOT-safe Publish(object) dispatch — no MakeGenericType, no Expression.Compile.
            sb.AppendLine($"            global::DSoftStudio.Mediator.NotificationObjectDispatch.Register<{group.Key}>(");
            sb.AppendLine("                static (notification, sp, publisher, ct) =>");
            sb.AppendLine("                {");
            sb.AppendLine($"                    var typed = ({group.Key})notification;");
            sb.AppendLine("                    if (publisher is not null)");
            sb.AppendLine("                    {");
            sb.AppendLine($"                        var handlers = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::DSoftStudio.Mediator.Abstractions.INotificationHandler<{group.Key}>>(sp);");
            sb.AppendLine("                        return publisher.Publish(handlers, typed, ct);");
            sb.AppendLine("                    }");
            sb.AppendLine("                    return global::DSoftStudio.Mediator.NotificationCachedDispatcher.DispatchSequential(typed, sp, ct);");
            sb.AppendLine("                });");
            sb.AppendLine();
        }

        // Freeze the dispatch table after all registrations.
        sb.AppendLine("            global::DSoftStudio.Mediator.NotificationObjectDispatch.Freeze();");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Extension method
        sb.AppendLine("    internal static class NotificationRegistryExtensions");
        sb.AppendLine("    {");
        sb.AppendLine("        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection PrecompileNotifications(");
        sb.AppendLine("            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("        {");
        sb.AppendLine("            NotificationRegistry.Register();");
        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Represents a notification handler registration.
    /// </summary>
    internal readonly struct NotificationHandlerInfo : System.IEquatable<NotificationHandlerInfo>
    {
        public string NotificationType { get; }
        public string HandlerType { get; }

        public NotificationHandlerInfo(string notificationType, string handlerType)
        {
            NotificationType = notificationType;
            HandlerType = handlerType;
        }

        public bool Equals(NotificationHandlerInfo other) =>
            NotificationType == other.NotificationType && HandlerType == other.HandlerType;

        public override bool Equals(object obj) =>
            obj is NotificationHandlerInfo other && Equals(other);

        public override int GetHashCode()
        {
            unchecked
            {
                return (NotificationType.GetHashCode() * 397) ^ HandlerType.GetHashCode();
            }
        }
    }
}
