// Copyright (c) DSoftStudio. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

#pragma warning disable RSEXPERIMENTAL002 // GetInterceptableLocation is experimental

namespace DSoftStudio.Mediator.Generators;

/// <summary>
/// Incremental generator that intercepts <c>ISender.Send&lt;TRequest, TResponse&gt;()</c> call sites
/// and replaces them with direct pipeline invocation — eliminating virtual dispatch, the
/// <c>Mediator.Send</c> method frame, and the delegate indirection on the hot path.
/// </summary>
[Generator]
public sealed class SendInterceptorGenerator : IIncrementalGenerator
{
    private const string SenderInterfaceMetadataName =
        "DSoftStudio.Mediator.Abstractions.ISender";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var callSites = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsSendCandidate(node),
                transform: static (ctx, ct) => GetInterceptInfo(ctx, ct))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!.Value);

        var collected = callSites.Collect();

        context.RegisterSourceOutput(collected, static (spc, calls) =>
        {
            if (calls.IsDefaultOrEmpty)
                return;

            var unique = calls.Distinct().ToList();
            var code = GenerateInterceptors(unique);

            spc.AddSource(
                "MediatorInterceptors.g.cs",
                SourceText.From(code, Encoding.UTF8));
        });
    }

    /// <summary>
    /// Lightweight syntactic check: is this an invocation of .Send with 2 type arguments?
    /// </summary>
    private static bool IsSendCandidate(SyntaxNode node)
    {
        return node is InvocationExpressionSyntax
        {
            Expression: MemberAccessExpressionSyntax
            {
                Name: GenericNameSyntax
                {
                    Identifier.Text: "Send",
                    TypeArgumentList.Arguments.Count: 2
                }
            }
        };
    }

    /// <summary>
    /// Semantic check: verify the call resolves to ISender.Send and extract type info + location.
    /// Uses GetInterceptableLocation API (Roslyn 4.12+) for the opaque location format.
    /// </summary>
    private static InterceptCallInfo? GetInterceptInfo(
        GeneratorSyntaxContext ctx,
        CancellationToken ct)
    {
        var invocation = (InvocationExpressionSyntax)ctx.Node;

        if (ctx.SemanticModel.GetSymbolInfo(invocation, ct).Symbol is not IMethodSymbol method)
            return null;

        if (method.Name != "Send" || method.TypeArguments.Length != 2)
            return null;

        var containingType = method.ContainingType;

        var senderInterface = ctx.SemanticModel.Compilation
            .GetTypeByMetadataName(SenderInterfaceMetadataName);

        if (senderInterface is null)
            return null;

        bool isSender = SymbolEqualityComparer.Default.Equals(containingType, senderInterface)
            || containingType.AllInterfaces.Any(i =>
                SymbolEqualityComparer.Default.Equals(i, senderInterface));

        if (!isSender)
            return null;

        // Use the new GetInterceptableLocation API (Roslyn 4.12+)
        var interceptableLocation = ctx.SemanticModel.GetInterceptableLocation(invocation, ct);
        if (interceptableLocation is null)
            return null;

        var requestType = method.TypeArguments[0]
            .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        var responseType = method.TypeArguments[1]
            .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        // GetInterceptsLocationAttributeSyntax returns the full attribute text:
        // [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "base64data")]
        var attributeSyntax = interceptableLocation.GetInterceptsLocationAttributeSyntax();

        return new InterceptCallInfo(
            attributeSyntax: attributeSyntax,
            requestType: requestType,
            responseType: responseType);
    }

    private static string GenerateInterceptors(List<InterceptCallInfo> calls)
    {
        var sb = new StringBuilder(2048);

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS9113 // Parameter is unread (required by compiler for interceptor attribute)");
        sb.AppendLine();

        // File-local InterceptsLocation attribute — version 1 opaque format
        sb.AppendLine("namespace System.Runtime.CompilerServices");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]");
        sb.AppendLine("    file sealed class InterceptsLocationAttribute(int version, string data) : global::System.Attribute");
        sb.AppendLine("    {");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("namespace DSoftStudio.Mediator.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    file static class SendInterceptors");
        sb.AppendLine("    {");

        // Group by (requestType, responseType) — multiple call sites can share one method
        var groups = calls
            .GroupBy(c => (c.RequestType, c.ResponseType))
            .ToList();

        int methodIndex = 0;
        foreach (var group in groups)
        {
            var reqType = group.Key.RequestType;
            var resType = group.Key.ResponseType;

            // Emit [InterceptsLocation] for each call site
            foreach (var call in group)
            {
                sb.Append("        ");
                sb.AppendLine(call.AttributeSyntax);
            }

            sb.Append("        internal static global::System.Threading.Tasks.ValueTask<");
            sb.Append(resType);
            sb.Append("> Send_");
            sb.Append(methodIndex);
            sb.Append("(this global::DSoftStudio.Mediator.Abstractions.ISender sender, ");
            sb.Append(reqType);
            sb.AppendLine(" request, global::System.Threading.CancellationToken cancellationToken = default)");
            sb.AppendLine("        {");
            sb.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(request);");
            sb.AppendLine("            var sp = ((global::DSoftStudio.Mediator.Abstractions.IServiceProviderAccessor)sender).ServiceProvider;");
            sb.AppendLine("            // Zero-delegate dispatch: static bool skips the GetService probe for the");
            sb.AppendLine("            // no-behaviors path (~0 ns branch vs ~5 ns failed DI lookup).");
            sb.Append("            if (global::DSoftStudio.Mediator.RequestDispatch<");
            sb.Append(reqType);
            sb.Append(", ");
            sb.Append(resType);
            sb.AppendLine(">.HasPipelineChain)");
            sb.AppendLine("            {");
            sb.Append("                var chain = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions");
            sb.Append(".GetService<global::DSoftStudio.Mediator.PipelineChainHandler<");
            sb.Append(reqType);
            sb.Append(", ");
            sb.Append(resType);
            sb.AppendLine(">>(sp);");
            sb.AppendLine("                if (chain is not null)");
            sb.AppendLine("                    return chain.Handle(request, cancellationToken);");
            sb.AppendLine("            }");
            sb.Append("            return global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions");
            sb.Append(".GetRequiredService<global::DSoftStudio.Mediator.Abstractions.IRequestHandler<");
            sb.Append(reqType);
            sb.Append(", ");
            sb.Append(resType);
            sb.AppendLine(">>(sp).Handle(request, cancellationToken);");
            sb.AppendLine("        }");
            sb.AppendLine();

            methodIndex++;
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    internal readonly struct InterceptCallInfo(
        string attributeSyntax,
        string requestType,
        string responseType) : System.IEquatable<InterceptCallInfo>
    {
        public string AttributeSyntax { get; } = attributeSyntax;
        public string RequestType { get; } = requestType;
        public string ResponseType { get; } = responseType;

        public bool Equals(InterceptCallInfo other) =>
            AttributeSyntax == other.AttributeSyntax;

        public override bool Equals(object obj) =>
            obj is InterceptCallInfo other && Equals(other);

        public override int GetHashCode() =>
            AttributeSyntax.GetHashCode();
    }
}
