// Copyright (c) DSoftStudio. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace DSoftStudio.Mediator.Generators;

[Generator]
public sealed class StreamGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlerInfos = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) =>
                    node is ClassDeclarationSyntax { BaseList: not null },
                transform: static (ctx, ct) => GetHandlerInfo(ctx, ct))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!.Value);

        var localCollected = handlerInfos.Collect();

        // Scan referenced assemblies for IStreamRequestHandler registrations
        var externalHandlers = context.CompilationProvider
            .Select(static (compilation, _) =>
            {
                var external = ReferencedAssemblyScanner.GetExternalStreamHandlers(compilation);
                var array = external
                    .Select(e => new StreamHandlerInfo(e.RequestType, e.ResponseType, e.HandlerType))
                    .OrderBy(static h => h.RequestType)
                    .ThenBy(static h => h.ResponseType)
                    .ToArray();
                return new EquatableArray<StreamHandlerInfo>(array);
            });

        var combined = localCollected.Combine(externalHandlers);

        context.RegisterSourceOutput(combined, static (spc, pair) =>
        {
            var (localHandlers, external) = pair;

            // Merge local + external, deduplicate
            var localList = localHandlers.IsDefaultOrEmpty
                ? Enumerable.Empty<StreamHandlerInfo>()
                : localHandlers.Distinct();

            var registrations = localList
                .Concat(external)
                .Distinct()
                .OrderBy(static h => h.RequestType)
                .ThenBy(static h => h.ResponseType)
                .ToList();

            var code = GenerateCode(registrations);

            spc.AddSource(
                "StreamRegistry.g.cs",
                SourceText.From(code, Encoding.UTF8));
        });
    }

    private static StreamHandlerInfo? GetHandlerInfo(
        GeneratorSyntaxContext ctx,
        CancellationToken ct)
    {
        var classDecl = (ClassDeclarationSyntax)ctx.Node;

        if (ctx.SemanticModel.GetDeclaredSymbol(classDecl, ct)
            is not INamedTypeSymbol symbol)
            return null;

        if (symbol.IsAbstract ||
            symbol.TypeKind != TypeKind.Class ||
            symbol.TypeParameters.Length > 0)
            return null;

        if (HandlerDiscovery.IsFileLocal(classDecl))
            return null;

        if (!HandlerDiscovery.TryGetStreamHandler(
                symbol,
                ct,
                out var requestType,
                out var responseType,
                out var handlerType))
            return null;

        return new StreamHandlerInfo(requestType, responseType, handlerType);
    }

    private static string GenerateCode(List<StreamHandlerInfo> registrations)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace DSoftStudio.Mediator");
        sb.AppendLine("{");

        sb.AppendLine("    internal static class StreamRegistry");
        sb.AppendLine("    {");

        sb.AppendLine("        public static void Register(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("        {");

        foreach (var handler in registrations)
        {
            sb.AppendLine(
                $"            global::DSoftStudio.Mediator.StreamDispatch<{handler.RequestType}, {handler.ResponseType}>.TryInitializeHandler(");

            sb.AppendLine(
                $"                static sp => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{handler.HandlerType}>(sp));");

            sb.AppendLine(
                $"            // Register the pre-wired chain handler for DI scope-level caching");
            sb.AppendLine(
                $"            global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddTransient<");
            sb.AppendLine(
                $"                global::DSoftStudio.Mediator.StreamPipelineChainHandler<{handler.RequestType}, {handler.ResponseType}>>(services);");

            sb.AppendLine(
                $"            RegisterStreamPipeline<{handler.RequestType}, {handler.ResponseType}>(services);");

            sb.AppendLine();
        }

        sb.AppendLine("        }");
        sb.AppendLine();

        // Generic helper that sets the stream dispatch pipeline
        sb.AppendLine("        private static void RegisterStreamPipeline<TRequest, TResponse>(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("            where TRequest : global::DSoftStudio.Mediator.Abstractions.IStreamRequest<TResponse>");
        sb.AppendLine("        {");
        sb.AppendLine("            // Route through StreamPipelineChainHandler which resolves handler + behaviors");
        sb.AppendLine("            // once per DI scope — no per-call GetServices().ToArray().");
        sb.AppendLine("            global::DSoftStudio.Mediator.StreamDispatch<TRequest, TResponse>.TryInitializePipeline(");
        sb.AppendLine("                static (request, sp, ct) =>");
        sb.AppendLine("                {");
        sb.AppendLine("                    var chain = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions");
        sb.AppendLine("                        .GetRequiredService<global::DSoftStudio.Mediator.StreamPipelineChainHandler<TRequest, TResponse>>(sp);");
        sb.AppendLine("                    return chain.Handle(request, ct);");
        sb.AppendLine("                });");
        sb.AppendLine("        }");

        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("    internal static class StreamRegistryExtensions");
        sb.AppendLine("    {");

        sb.AppendLine(
            "        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection PrecompileStreams(");

        sb.AppendLine(
            "            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");

        sb.AppendLine("        {");

        sb.AppendLine("            StreamRegistry.Register(services);");
        sb.AppendLine("            return services;");

        sb.AppendLine("        }");

        sb.AppendLine("    }");

        sb.AppendLine("}");

        return sb.ToString();
    }

    internal readonly struct StreamHandlerInfo : System.IEquatable<StreamHandlerInfo>
    {
        public string RequestType { get; }
        public string ResponseType { get; }
        public string HandlerType { get; }

        public StreamHandlerInfo(string requestType, string responseType, string handlerType)
        {
            RequestType = requestType;
            ResponseType = responseType;
            HandlerType = handlerType;
        }

        public bool Equals(StreamHandlerInfo other) =>
            RequestType == other.RequestType &&
            ResponseType == other.ResponseType &&
            HandlerType == other.HandlerType;

        public override bool Equals(object obj) =>
            obj is StreamHandlerInfo other && Equals(other);

        public override int GetHashCode()
        {
            unchecked
            {
                int hash = RequestType.GetHashCode();
                hash = (hash * 397) ^ ResponseType.GetHashCode();
                hash = (hash * 397) ^ HandlerType.GetHashCode();
                return hash;
            }
        }
    }
}
