<Project>

	<PropertyGroup>
		<!-- Strong naming: all assemblies signed with the same key -->
		<SignAssembly>true</SignAssembly>
		<AssemblyOriginatorKeyFile>$(MSBuildThisFileDirectory)DSoftStudio.Mediator.snk</AssemblyOriginatorKeyFile>
		<PublicKey>002400000480000094000000060200000024000052534131000400000100010019699024814BEE85BD5478A6193AF052BD147EA26D7EA7DA4099C5D2822CCEC95C1A717BADAC3EDE2ADF868BE84976E070EAFE0B0B179CE42D741B6802FDC8F0E1399D827CE7AEB5B1BE1D1ADDB90CCC1707DA4C07A8E16DF364F65B2134525443D1915946F40478636380FFD1790F1E6E35D790DF144B353FE7F828BA9FEAE0</PublicKey>
		<PublicKeyToken>6c7e753832e8eb05</PublicKeyToken>
	</PropertyGroup>

</Project>
